### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by ipajen** [MariaDB/wordpress-mariadb-health-checks#13]
MariaDB Health Checks
Version 1.0.0 | By [Cloudfest Hackathon 2023 Team](https://github.com/itsdarkmars/hackathon) | [Visit plugin site](http://github.com/ahmu83/mariadb-health-checks/)

both links seems to referring to this page, maybe better to update the links?

**Comment by LinuxJedi** [comment]
Good call, I missed that.
