### ISSUE TITLE
Upload to SVN tags

### ISSUE THREAD

**Issue by javiercasares** [MariaDB/wordpress-mariadb-health-checks#20]
In the WordPress SVN there is the “trunk” folder but also the “tags” folder. There should be a version number folder (like “1.0.1”) and a copy of that version, so you can return to older versions with some plugins or having a ZIP history version.

So, when a new version is launched, there is a replacement for all the trunk files, and a new folder with the new version in the tags.

**Comment by LinuxJedi** [comment]
Version 1.0.1 has now been tagged: https://plugins.trac.wordpress.org/browser/mariadb-health-checks/tags/1.0.1?rev=2892581
