### ISSUE TITLE
PHP 8.2 database error SHOW command denied

### ISSUE THREAD

**Issue by ipajen** [MariaDB/wordpress-mariadb-health-checks#5]
### Environment
- WordPress: 6.2-RC5
- PHP: 8.2.3
- Server: LiteSpeed
- Database: mysqli (Server: 10.4.28-MariaDB / Client: mysqlnd 8.2.3)
- MariaDB Health Checks 1.0.0
- Shared Hosting

`WordPress database error SHOW command denied to user 'khaotiptha_wp5'@'localhost' for table `mysql`.`table_stats` for query show create table mysql.table_stats; made by require_once('wp-admin/admin.php'), do_action('tools_page_mdbhc'), WP_Hook->do_action, WP_Hook->apply_filters, MDBHC\AdminScreen->admin_screen_template, mdbhc__template, mdbhc_template, mdbhc_inc, include('/plugins/wordpress-mariadb-health-checks-1.0.0/templates/admin/main.php'), mdbhc__template, mdbhc_template, mdbhc_inc, include('/plugins/wordpress-mariadb-health-checks-1.0.0/templates/admin/notices.php'), MDBHC\Histograms->check, MDB_DB->query`

**Comment by LinuxJedi** [comment]
This one is to be expected if you have debugging turned on. The source takes action based on this.
